#!/bin/bash
# -----------------------------------------------------------------------------
# docker-minecraft /start script
#
# Authors: Isaac Bythewood
# Updated: Oct 21st, 2014
# -----------------------------------------------------------------------------


# Copy over the base database to our data directory if it doesn't exist
if [ ! -f /data/minecraft_server.jar ]
then
    cd /data
    cp /usr/local/etc/minecraft/ops.txt .
    cp /usr/local/etc/minecraft/white-list.txt .
    cp /usr/local/etc/minecraft/server.properties .
    curl http://dl.bukkit.org/downloads/craftbukkit/get/02389_1.6.4-R2.0/craftbukkit.jar -o minecraft_server.jar
fi


# Run supervisor which maintains the mumble server
/usr/bin/supervisord

